var StudentManagerApp = angular.module('StudentManagerApp',[
        'ui.router',
        'ngResource',
        'StudentManagerControllers',
        'StudentManagerServices'
    ]
);

StudentManagerApp.config(function($stateProvider,$httpProvider){
    $stateProvider.state('students',{
        url:'/students',
        templateUrl:'app/partials/students.html',
        controller:'StudentListController'
    }).state('viewStudent',{
       url:'/students/:id/view',
       templateUrl:'app/partials/student-view.html',
       controller:'StudentViewController'
    }).state('newStudent',{
        url:'/students/new',
        templateUrl:'app/partials/student-add.html',
        controller:'studentCreateController'
    }).state('editStudent',{
        url:'/students/:id/edit',
        templateUrl:'app/partials/student-edit.html',
        controller:'StudentEditController'
    });
}).run(function($state){
   $state.go('students');
});